
name: Build Windows

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build: 
    strategy:
      matrix:
        os: [windows-latest]
        build_type: [Release, Debug]
        arch: [Win32, x64]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup MSbuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build
        run: |
                mkdir build_${{ matrix.build_type }}
                cd build_${{ matrix.build_type }}
                cmake -G "Visual Studio 17 2022" -A ${{ matrix.arch }} ..
                msbuild ALL_BUILD.vcxproj /property:Configuration=${{ matrix.build_type }}

      - name: Upload Artifacts 
        uses: actions/upload-artifact@v3
        with: 
          name: ${{ matrix.build_type }}_${{ matrix.arch }}
          path: |
            build_${{ matrix.build_type }}/${{ matrix.build_type }}/*
            build_${{ matrix.build_type }}/win/tests/${{ matrix.build_type }}/*

#       - name: Create Release
#         if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
#         uses: ncipollo/release-action@v1
#         with:
#             artifacts: "deploy/*"
#             token: ${{ secrets.GITHUB_TOKEN }}
#             allowUpdates: true
